//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputInfo
    {
        public int ID { get; set; }
        public string Kabunet { get; set; }
        public System.DateTime Time { get; set; }
        public string Doctor { get; set; }
        public string Positutel { get; set; }
    }
}
